import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Built-in React Hooks",
  description:
    "Generated by create next app + typescript. Hooks let you use different React features from your components. You can either use the built-in Hooks or combine them to build your own. This page lists all built-in Hooks in React.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
        {/* <footer>
          <p>
            Hooks let you use different React features from your components. You
            can either use the built-in Hooks or combine them to build your own.
            This page lists all built-in Hooks in React.
          </p>
        </footer> */}
      </body>
    </html>
  );
}
